### ISSUE TITLE
Server gets down

### ISSUE THREAD

**Issue by incleaf** [Flative/jude#26]
![image](https://cloud.githubusercontent.com/assets/7221609/21806690/2bf4fcc2-d77e-11e6-9569-72322d43f93a.png)

```
* Running on
* ws://0.0.0.0:8000/ws
* http://0.0.0.0:8000/

(Press CTRL+C to quit)
panic: concurrent write to websocket connection

goroutine 51 [running]:
panic(0x736100, 0xc8200635f0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
jude/backend/vendor/github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc820034ce8, 0xc820254601, 0xc820254840, 0x0, 0x3c0, 0x0, 0x0)
	/home/ubuntu/Go/src/jude/backend/vendor/github.com/gorilla/websocket/conn.go:536 +0x5bf
jude/backend/vendor/github.com/gorilla/websocket.(*Conn).WriteMessage(0xc820091560, 0x1, 0xc820254840, 0x0, 0x3c0, 0x0, 0x0)
	/home/ubuntu/Go/src/jude/backend/vendor/github.com/gorilla/websocket/conn.go:672 +0x325
main.(*Manager).broadcast(0xc8200d0620, 0xc820254600, 0x240, 0x600, 0x0, 0x0)
	/home/ubuntu/Go/src/jude/backend/manager.go:27 +0xf0
main.main.func1.1(0xc8200d0620, 0xc820232000)
	/home/ubuntu/Go/src/jude/backend/main.go:50 +0x141
created by main.main.func1
	/home/ubuntu/Go/src/jude/backend/main.go:55 +0x1e0
exit status 2
```

**Comment by incleaf** [comment]
Fixed (https://github.com/Flative/jude/commit/9ca170bc17d7fe67fe72604f649581926aa04973)
